## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if not bld.env['ENABLE_EXAMPLES']:
        return;

    obj = bld.create_ns3_program('npaf-multi-run-example', ['npaf','applications','aodv','olsr','dsr','dsdv','internet','network','wifi','wave','config-store','stats'])
    obj.source = 'npaf-multi-run-example.cc'

